/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DeliveryDAO;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import model.Delivery;
import util.ConexaoBanco;
import util.ModeloTabela;

/**
 *
 * @author Escritorio
 */
public class FormDelivery extends javax.swing.JFrame {
    private final ConexaoBanco conexao = new ConexaoBanco();
    private FormVendaDelivery formDelivery;
    private FormProdutos formProdutos;
    private FormClientes formCliente;
    private FormCupomDelivery cupomDelivery;
    private FormUsuarios formUsuario;
    private RelatorioVenda relatorio;
    private float totalProdutos , entrega;
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private final DateFormat DATA = new SimpleDateFormat("yyyy-MM-dd");
    private Date data;
    /**
     * Creates new form FormDelivery
     */
    public FormDelivery() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        dataAtual();
       
        //listarTabelaProduto();
    }
    public String retornaData(){
        data = new Date();
        String aux = DATA.format(data);
        return aux;
        
    }
    public void dataAtual(){
        listarTabelaDelivery(retornaData());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_delivery = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        bt_baixar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_observacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_entrega = new javax.swing.JTextField();
        txt_troco = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbl_total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        bt_delivery = new javax.swing.JButton();
        bt_produtos = new javax.swing.JButton();
        bt_clientes = new javax.swing.JButton();
        bt_imprimir = new javax.swing.JButton();
        bt_imprimir1 = new javax.swing.JButton();
        bt_configuracao = new javax.swing.JButton();
        bt_configuracao1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bt_imprimir2 = new javax.swing.JButton();
        txf_pesquisar = new javax.swing.JFormattedTextField();
        bt_relatorio = new javax.swing.JButton();
        bt_usuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esfihas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(170, 169, 149));

        tabela_delivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela_delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_deliveryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_delivery);

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela_produtos);

        bt_baixar.setBackground(new java.awt.Color(170, 169, 149));
        bt_baixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cloud-computing(1).png"))); // NOI18N
        bt_baixar.setToolTipText("Baixar Pedido");
        bt_baixar.setEnabled(false);
        bt_baixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_baixarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Dados do Cliente"));

        txt_nome.setEditable(false);
        txt_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nome.setEnabled(false);

        txt_endereco.setEditable(false);
        txt_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_endereco.setEnabled(false);
        txt_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enderecoActionPerformed(evt);
            }
        });

        txt_telefone.setEditable(false);
        txt_telefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_telefone.setEnabled(false);

        jLabel3.setText("NOME:");

        jLabel4.setText("ENDEREÇO:");

        jLabel5.setText("TELEFONE:");

        txt_observacao.setEditable(false);
        txt_observacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_observacao.setEnabled(false);

        jLabel9.setText("OBSERVAÇÃO:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addComponent(txt_nome))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Dados da Entrega"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Entrega: R$");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Troco: R$");

        txt_entrega.setEditable(false);

        txt_troco.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(txt_troco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valor"));

        lbl_total.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(0, 153, 153));
        lbl_total.setText("0,00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("R$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_cancelar.setBackground(new java.awt.Color(170, 169, 149));
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cloud-computing.png"))); // NOI18N
        bt_cancelar.setToolTipText("Cancelar Pedido");
        bt_cancelar.setEnabled(false);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_baixar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_baixar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        bt_delivery.setBackground(new java.awt.Color(170, 169, 149));
        bt_delivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/scooter(2).png"))); // NOI18N
        bt_delivery.setToolTipText("Cadastrar Pedido");
        bt_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deliveryActionPerformed(evt);
            }
        });

        bt_produtos.setBackground(new java.awt.Color(170, 169, 149));
        bt_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fast-food.png"))); // NOI18N
        bt_produtos.setToolTipText("Cadastrar Produtos");
        bt_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produtosActionPerformed(evt);
            }
        });

        bt_clientes.setBackground(new java.awt.Color(170, 169, 149));
        bt_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-friend.png"))); // NOI18N
        bt_clientes.setToolTipText("Cadastrar Cliente");
        bt_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clientesActionPerformed(evt);
            }
        });

        bt_imprimir.setBackground(new java.awt.Color(170, 169, 149));
        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/printer.png"))); // NOI18N
        bt_imprimir.setToolTipText("Imprimir Pedido");
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });

        bt_imprimir1.setBackground(new java.awt.Color(170, 169, 149));
        bt_imprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        bt_imprimir1.setToolTipText("Atualizar");
        bt_imprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimir1ActionPerformed(evt);
            }
        });

        bt_configuracao.setBackground(new java.awt.Color(170, 169, 149));
        bt_configuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gear.png"))); // NOI18N
        bt_configuracao.setToolTipText("Configuração");
        bt_configuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_configuracaoActionPerformed(evt);
            }
        });

        bt_configuracao1.setBackground(new java.awt.Color(170, 169, 149));
        bt_configuracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money.png"))); // NOI18N
        bt_configuracao1.setToolTipText("Caixa");
        bt_configuracao1.setEnabled(false);
        bt_configuracao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_configuracao1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Pesquisar por Data:");

        bt_imprimir2.setBackground(new java.awt.Color(170, 169, 149));
        bt_imprimir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search(1).png"))); // NOI18N
        bt_imprimir2.setToolTipText("Pesquisar");
        bt_imprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimir2ActionPerformed(evt);
            }
        });

        try {
            txf_pesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bt_relatorio.setBackground(new java.awt.Color(170, 169, 149));
        bt_relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/analytics.png"))); // NOI18N
        bt_relatorio.setToolTipText("Atualizar");
        bt_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_relatorioActionPerformed(evt);
            }
        });

        bt_usuarios.setBackground(new java.awt.Color(170, 169, 149));
        bt_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        bt_usuarios.setToolTipText("Atualizar");
        bt_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_usuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bt_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_configuracao1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txf_pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_imprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_configuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_imprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(4, 4, 4)
                                .addComponent(txf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_imprimir2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_configuracao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_usuarios, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_relatorio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_configuracao1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_imprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_clientes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_produtos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_delivery, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_imprimir1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deliveryActionPerformed
       if (formDelivery == null) {
            formDelivery = new FormVendaDelivery();
        }
        formDelivery.limpar();
        formDelivery.setVisible(true);
        
    }//GEN-LAST:event_bt_deliveryActionPerformed

    private void bt_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produtosActionPerformed
         if (formProdutos == null) {
            formProdutos = new FormProdutos();
        }

        formProdutos.setVisible(true);
    }//GEN-LAST:event_bt_produtosActionPerformed

    private void bt_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clientesActionPerformed
         if (formCliente == null) {
            formCliente = new FormClientes();
        }

        formCliente.setVisible(true);
    }//GEN-LAST:event_bt_clientesActionPerformed

    private void tabela_deliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_deliveryMouseClicked
        String id = ""+tabela_delivery.getValueAt(tabela_delivery.getSelectedRow(), 0);
        bt_baixar.setEnabled(true);
        bt_cancelar.setEnabled(true);
        conexao.conecta();
       
        conexao.executaSQL("SELECT * FROM tb_clientes INNER JOIN tb_delivery ON "
                + "tb_delivery.idCliente = tb_clientes.codigo_cliente WHERE codigo_delivery = '"+id+"'");
        //bt_editar.setEnabled(true);
        //bt_excluir.setEnabled(true);
        try {
            conexao.rs.first();
            txt_nome.setText(conexao.rs.getString("nome"));
            txt_endereco.setText(conexao.rs.getString("endereco")+" N. "+ conexao.rs.getString("numero")
                +"  "+ conexao.rs.getString("complemento")+" - "+conexao.rs.getString("bairro"));
            txt_telefone.setText(conexao.rs.getString("telefone"));
            lbl_total.setText(decimal.format(conexao.rs.getDouble("total")));
            txt_troco.setText(decimal.format(conexao.rs.getDouble("troco")));
            txt_entrega.setText(decimal.format(conexao.rs.getDouble("entrega")));
            txt_observacao.setText(conexao.rs.getString("observacao"));
            String cartao = conexao.rs.getString("cartao");
            listarTabelaProduto(id);
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabela_deliveryMouseClicked

    private void txt_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enderecoActionPerformed

    private void bt_baixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_baixarActionPerformed
        // TODO add your handling code here:
        
       String id = ""+tabela_delivery.getValueAt(tabela_delivery.getSelectedRow(), 0);
   
    if (tabela_delivery.getSelectedRow() > -1){
        if (JOptionPane.showConfirmDialog(this, "Deseja Baixar o Pedido Selecionado?","Gold Food",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            FormPagamentoDelivery formPagamentoDelivery = new FormPagamentoDelivery(this);
            Delivery delivery = new Delivery();
      
    try {
            conexao.conecta();
                        
            conexao.executaSQL("select * from tb_delivery where codigo_delivery = '"+id +"'");
            conexao.rs.first();
            
           
            if(conexao.rs.getString("status").equals("ABERTO")){
                delivery.setCodigo(conexao.rs.getInt("codigo_delivery"));
               
                entrega = conexao.rs.getFloat("entrega");
                totalProdutos = conexao.rs.getFloat("total");
                delivery.setEntrega(entrega);
                
                delivery.setTotalPedido(totalProdutos - entrega);
                
                
                formPagamentoDelivery.itensVenda(delivery, "alterar");
                formPagamentoDelivery.setVisible(true);
                
                
            }else{
                JOptionPane.showMessageDialog(null,"O pedido não pode ser Baixado!" );
            }
    
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
        }
    
    }//GEN-LAST:event_bt_baixarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
    String senha = JOptionPane.showInputDialog(this, "Digite a senha do Aministrador!");
    
    if(!senha.equals("masterfood")){
        JOptionPane.showMessageDialog(this, "Senha Inválida!");
    }else{
            
            
    String id = ""+tabela_delivery.getValueAt(tabela_delivery.getSelectedRow(), 0);
    if (tabela_delivery.getSelectedRow() > -1){
        if (JOptionPane.showConfirmDialog(this, "Deseja Cancelar o Pedido Selecionado?","Gold Food",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
    try {
            conexao.conecta();
                        
            conexao.executaSQL("select * from tb_delivery where codigo_delivery = '"+id +"'");
            conexao.rs.first();
            Delivery delivery = new Delivery();
            DeliveryDAO deliveryDAO = new DeliveryDAO();
            if(conexao.rs.getString("status").equals("ABERTO")){
                delivery.setStatus("CANCELADO");
                delivery.setCodigo(conexao.rs.getInt("codigo_delivery"));
                deliveryDAO.alterarDelivery(delivery);
                
                dataAtual();
            }else{
                JOptionPane.showMessageDialog(null,"O pedido não pode ser cancelado!" );
            }
            
            
    
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
        }
        }
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_imprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimir1ActionPerformed
        dataAtual();
    }//GEN-LAST:event_bt_imprimir1ActionPerformed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        // TODO add your handling code here:
          String idDelivery = ""+tabela_delivery.getValueAt(tabela_delivery.getSelectedRow(), 0);
         if (tabela_delivery.getSelectedRow() != -1) {
            if (cupomDelivery == null) {
                cupomDelivery = new FormCupomDelivery();
            }
            cupomDelivery.setNome(txt_nome.getText());
            cupomDelivery.setEndereco(txt_endereco.getText());
            cupomDelivery.setTelefone(txt_telefone.getText());
            cupomDelivery.setTroco(txt_troco.getText());
            cupomDelivery.setModal(true);
            cupomDelivery.setItensPedido((ModeloTabela) tabela_produtos.getModel());
            cupomDelivery.setTotalDelivery(lbl_total.getText());
            cupomDelivery.setIdDelivery(idDelivery);
            cupomDelivery.preencheLista();
            
            cupomDelivery.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Item Vendido!",
                    "GOLD FOOD", JOptionPane.INFORMATION_MESSAGE);
        }
                                              
    }//GEN-LAST:event_bt_imprimirActionPerformed

    private void bt_configuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_configuracaoActionPerformed
        // TODO add your handling code here:
        FormLoja formLoja = new FormLoja();
        formLoja.setVisible(true);
    }//GEN-LAST:event_bt_configuracaoActionPerformed
   
    private void bt_configuracao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_configuracao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_configuracao1ActionPerformed

    private void bt_imprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimir2ActionPerformed
        if(!txf_pesquisar.getText().isEmpty()){
            
            String dia, mes, ano, res;
            res = txf_pesquisar.getText();
            dia = res.substring(0, res.indexOf('/'));
            mes = res.substring(res.indexOf('/')+1, res.lastIndexOf('/'));
            ano = res.substring(res.lastIndexOf('/')+1, res.length());
        
            res = ano+'-'+mes+'-'+dia;
            listarTabelaDelivery(res);
        }else{
            dataAtual();
        }
    }//GEN-LAST:event_bt_imprimir2ActionPerformed

    private void bt_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_relatorioActionPerformed
     String senha = JOptionPane.showInputDialog(this, "Digite a senha do Aministrador!");
    
    if(!senha.equals("masterfood")){
        JOptionPane.showMessageDialog(this, "Senha Inválida!");
    }else{
        if (relatorio == null) {
            relatorio = new RelatorioVenda();
        }

        relatorio.setVisible(true);
     }
    }//GEN-LAST:event_bt_relatorioActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        dataAtual();
    }//GEN-LAST:event_formWindowGainedFocus

    private void bt_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_usuariosActionPerformed
        if (formUsuario == null) {
            formUsuario = new FormUsuarios();
        }

        formUsuario.setVisible(true);
    }//GEN-LAST:event_bt_usuariosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDelivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_baixar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_clientes;
    private javax.swing.JButton bt_configuracao;
    private javax.swing.JButton bt_configuracao1;
    private javax.swing.JButton bt_delivery;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JButton bt_imprimir1;
    private javax.swing.JButton bt_imprimir2;
    private javax.swing.JButton bt_produtos;
    private javax.swing.JButton bt_relatorio;
    private javax.swing.JButton bt_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tabela_delivery;
    private javax.swing.JTable tabela_produtos;
    private javax.swing.JFormattedTextField txf_pesquisar;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_entrega;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_observacao;
    private javax.swing.JTextField txt_telefone;
    private javax.swing.JTextField txt_troco;
    // End of variables declaration//GEN-END:variables

    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); 

        String str = (String) value;
        if ("ABERTO".equals(str)) {
            c.setForeground(Color.GREEN);
            
        } else if("FECHADO".equals(str)) {
            c.setForeground(Color.BLUE);
            
        }else if("CANCELADO".equals(str)) {
            c.setForeground(Color.RED);
         
        }
        return c;
    }
};
    
    private void listarTabelaDelivery(String data) {
        String sql = "SELECT * FROM tb_clientes INNER JOIN tb_delivery ON "
                + "tb_delivery.idCliente = tb_clientes.codigo_cliente WHERE data = '"+data+"'ORDER BY status";
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código","Data","Cliente","Observação","Valor","Troco","Status"};
        conexao.conecta();
        conexao.executaSQL(sql);
        
               
        try {
            conexao.rs.first();
            do{
                dados.add(new Object[]{
                                                       conexao.rs.getInt("codigo_delivery"),
                                                       conexao.rs.getString("data"),
                                                       conexao.rs.getString("nome"),
                                                       conexao.rs.getString("observacao"),
                                                       decimal.format(conexao.rs.getDouble("total")),
                                                       decimal.format(conexao.rs.getDouble("troco")),
                                                       conexao.rs.getString("status"),
                                                       });
                
            
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            System.out.println("Erro ao Preencher a Tabela"+ ex);
        }
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabela_delivery.setModel(modelo);
         tabela_delivery.getColumnModel().getColumn(0).setPreferredWidth(80);
         tabela_delivery.getColumnModel().getColumn(0).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(1).setPreferredWidth(200);
         tabela_delivery.getColumnModel().getColumn(1).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(2).setPreferredWidth(300);
         tabela_delivery.getColumnModel().getColumn(2).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(3).setPreferredWidth(200);
         tabela_delivery.getColumnModel().getColumn(3).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(4).setPreferredWidth(200);
         tabela_delivery.getColumnModel().getColumn(4).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(5).setPreferredWidth(200);
         tabela_delivery.getColumnModel().getColumn(5).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(6).setPreferredWidth(200);
         tabela_delivery.getColumnModel().getColumn(6).setResizable(false);
         tabela_delivery.getColumnModel().getColumn(6).setCellRenderer(renderer);
                             
         tabela_delivery.getTableHeader().setReorderingAllowed(false);
         tabela_delivery.setAutoResizeMode( tabela_delivery.AUTO_RESIZE_OFF);
         tabela_delivery.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void listarTabelaProduto(String id) {
       
        String sql = "SELECT * FROM tb_produtosdelivery INNER JOIN "
                + "tb_produtos ON tb_produtos.codigo_produto = tb_produtosdelivery.id_produto WHERE id_delivery = '"+id+"'";
        
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código","Descrição","Quant","Preço","Total","Opcional"};
        conexao.conecta();
        conexao.executaSQL(sql);
        
               
        try {
            conexao.rs.first();
            do{
                dados.add(new Object[]{
                                                       conexao.rs.getInt("codigo_produto"),
                                                       conexao.rs.getString("descricao"),
                                                       conexao.rs.getString("quantidade"),
                                                       decimal.format(conexao.rs.getDouble("preco_produto")),
                                                       decimal.format(conexao.rs.getDouble("total_produto")),
                                                       conexao.rs.getString("opcional"),
                                                       });
            
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            System.out.println("Erro ao Preencher a Tabela"+ ex);
        }
        
        
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabela_produtos.setModel(modelo);
         tabela_produtos.getColumnModel().getColumn(0).setPreferredWidth(80);
         tabela_produtos.getColumnModel().getColumn(0).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(1).setPreferredWidth(300);
         tabela_produtos.getColumnModel().getColumn(1).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(2).setPreferredWidth(100);
         tabela_produtos.getColumnModel().getColumn(2).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(3).setPreferredWidth(100);
         tabela_produtos.getColumnModel().getColumn(3).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(4).setPreferredWidth(100);
         tabela_produtos.getColumnModel().getColumn(4).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(5).setPreferredWidth(300);
         tabela_produtos.getColumnModel().getColumn(5).setResizable(false);
               
                           
         tabela_produtos.getTableHeader().setReorderingAllowed(false);
         tabela_produtos.setAutoResizeMode( tabela_produtos.AUTO_RESIZE_OFF);
         tabela_produtos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    
}
