/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ProdutosDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Produto;
import util.ConexaoBanco;
import util.ModeloTabela;
import util.UpperCaseField;

/**
 * @author Escritorio
 */
public class FormProdutos extends javax.swing.JFrame {
    private Produto produto = new Produto();
    private final ProdutosDAO pDAO = new ProdutosDAO();
    private final ConexaoBanco conexao = new ConexaoBanco();
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    
    /** Creates new form formDelivery */
    public FormProdutos() {
        initComponents();
        listarTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_icone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSair = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_descricao = new UpperCaseField();
        txt_preco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_referencia = new UpperCaseField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Produtos");

        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esfihas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addGap(81, 81, 81)
                        .addComponent(lbSair)
                        .addGap(483, 483, 483))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_icone)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_icone)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIÇÃO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PREÇO:");

        txt_descricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_descricao.setEnabled(false);
        txt_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descricaoKeyPressed(evt);
            }
        });

        txt_preco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_preco.setEnabled(false);
        txt_preco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_precoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("REFERÊNCIA:");

        txt_referencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_referencia.setEnabled(false);
        txt_referencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_referenciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        bt_novo.setBackground(new java.awt.Color(170, 169, 149));
        bt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        bt_novo.setText("NOVO");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setBackground(new java.awt.Color(170, 169, 149));
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        bt_salvar.setText("SALVAR");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        bt_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_salvarKeyPressed(evt);
            }
        });

        bt_editar.setBackground(new java.awt.Color(170, 169, 149));
        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit_text.png"))); // NOI18N
        bt_editar.setText("EDITAR");
        bt_editar.setEnabled(false);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setBackground(new java.awt.Color(170, 169, 149));
        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eraser.png"))); // NOI18N
        bt_excluir.setText("EXCLUIR");
        bt_excluir.setEnabled(false);
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_sair.setBackground(new java.awt.Color(170, 169, 149));
        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        bt_sair.setText("SAIR");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluir)
                    .addComponent(bt_editar)
                    .addComponent(bt_salvar)
                    .addComponent(bt_novo)
                    .addComponent(bt_sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(826, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked
        
    }//GEN-LAST:event_lbSairMouseClicked

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        //sair da tela
        desativarComponentes();
        bt_novo.setEnabled(true);
        limparComponentes();
        this.dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        //função do botão novo
        ativarComponentes();
        txt_descricao.requestFocus();
        bt_novo.setEnabled(false);
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // funcão do botão salvar
        salvar();
        desativarComponentes();
        limparComponentes();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //Carregar os componentes quanto clicar na linha da tabela
        ativarComponentes();
        String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
        conexao.conecta();
       
        conexao.executaSQL("select * from tb_produtos where codigo_produto = '"+id +"'");
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        try {
            conexao.rs.first();
            txt_descricao.setText(conexao.rs.getString("descricao"));
            txt_preco.setText(String.valueOf(decimal.format(conexao.rs.getDouble("preco"))));
            txt_referencia.setText(conexao.rs.getString("referencia"));

            
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // evento para botão alterar
         String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
                         
    try {
            conexao.conecta();
            conexao.executaSQL("select * from tb_produtos where codigo_produto = '"+id +"'");
            conexao.rs.first();
            System.out.println(conexao.rs.first());
            produto = new Produto();
            
            produto.setCodigo(conexao.rs.getInt("codigo_produto"));
            produto.setDescrição(txt_descricao.getText());
            produto.setPreco(Double.parseDouble(txt_preco.getText().replace(",", ".")));
            produto.setReferencia(txt_referencia.getText());
            pDAO.alterarProdutos(produto);
            
            JOptionPane.showMessageDialog(null, "Cliente Alterado!");
            
            listarTabela();
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
       desativarComponentes();
       limparComponentes();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        // evento para excluir
           String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
           if (JOptionPane.showConfirmDialog(this, "Deseja Excluir o produto Selecionado?","Gold Food",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
          
    try {
            conexao.conecta();
                        
            conexao.executaSQL("select * from tb_produtos where codigo_produto = '"+id +"'");
            conexao.rs.first();
            produto.setCodigo(conexao.rs.getInt("codigo_produto"));
            pDAO.excluirProdutos(produto);
            JOptionPane.showMessageDialog(null, "Cliente Excluido!");
            
            listarTabela();
    
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void txt_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descricaoKeyPressed
        if (evt.getKeyCode() == 10){
           txt_referencia.requestFocus();
        }
    }//GEN-LAST:event_txt_descricaoKeyPressed

    private void txt_referenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_referenciaKeyPressed
        if (evt.getKeyCode() == 10){
           txt_preco.requestFocus();
        }
    }//GEN-LAST:event_txt_referenciaKeyPressed

    private void txt_precoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precoKeyPressed
       if (evt.getKeyCode() == 10){
           bt_salvar.requestFocus();
        }
    }//GEN-LAST:event_txt_precoKeyPressed

    private void bt_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_salvarKeyPressed
        if (evt.getKeyCode() == 10){
            salvar();
        }
    }//GEN-LAST:event_bt_salvarKeyPressed
    public void ativarComponentes(){
        //Ativar as caixas
        txt_descricao.setEnabled(true);
        txt_preco.setEnabled(true);
        txt_referencia.setEnabled(true);
    }
    public void desativarComponentes(){
        //Desativar as caixas
        txt_descricao.setEnabled(false);
        txt_preco.setEnabled(false);
        txt_referencia.setEnabled(false);
        bt_editar.setEnabled(false);
        bt_salvar.setEnabled(false);
        bt_excluir.setEnabled(false);
    }
    public void limparComponentes(){
        //limpar as caixas
        txt_descricao.setText("");
        txt_preco.setText("");
        txt_referencia.setText("");
    }
    public void salvar(){
        if(!txt_descricao.getText().isEmpty()|| !txt_preco.getText().isEmpty()){
             produto.setDescrição(txt_descricao.getText());
             produto.setPreco(Double.parseDouble(txt_preco.getText().replaceAll(",", ".")));
             produto.setReferencia(txt_referencia.getText());
             pDAO.SalvarProdutos(produto);
             listarTabela();
             limparComponentes();
             desativarComponentes();
        }else{
            JOptionPane.showMessageDialog(null, "Preenche os campos Descrição e Preço");
        }
        bt_novo.setEnabled(true);
        bt_salvar.setEnabled(false);
    }
    
    public void listarTabela(){
        String sql = "SELECT * FROM tb_produtos";
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código","Referência","Descrição","Preço"};
        conexao.conecta();
        conexao.executaSQL(sql);
        
               
        try {
            conexao.rs.first();
            do{
                dados.add(new Object[]{
                                                       conexao.rs.getInt("codigo_produto"),
                                                       conexao.rs.getString("referencia"),
                                                       conexao.rs.getString("descricao"),
                                                       String.valueOf(decimal.format(conexao.rs.getDouble("preco"))),
                                                       });
            
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            System.out.println("Erro ao Preencher a Tabela"+ ex);
        }
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabela.setModel(modelo);
         tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
         tabela.getColumnModel().getColumn(0).setResizable(false);
         tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
         tabela.getColumnModel().getColumn(1).setResizable(false);
         tabela.getColumnModel().getColumn(2).setPreferredWidth(300);
         tabela.getColumnModel().getColumn(2).setResizable(false);
         tabela.getColumnModel().getColumn(3).setPreferredWidth(200);
         tabela.getColumnModel().getColumn(3).setResizable(false);
                             
         tabela.getTableHeader().setReorderingAllowed(false);
         tabela.setAutoResizeMode( tabela.AUTO_RESIZE_OFF);
         tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
       
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbSair;
    private javax.swing.JLabel lbl_icone;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_referencia;
    // End of variables declaration//GEN-END:variables

}
