/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientesDAO;
import controller.DeliveryDAO;
import controller.ProdutosDAO;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Delivery;
import model.Produto;
import util.ConexaoBanco;
import util.ModeloTabela;

/**
 *
 * @author Escritorio
 */
public class FormVendaDelivery extends javax.swing.JFrame {
    private FormClientes formCli = new FormClientes();
    private final String numeros = "0123456789";
    private final Cliente cliente = new Cliente();
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private final ClientesDAO  clienteDAO = new ClientesDAO();
    private final Produto produto = new Produto();
    private final ProdutosDAO produtoDAO = new ProdutosDAO();
    private DefaultTableModel tabelaAux;
    private Object linhas[];
    private Delivery delivery = new Delivery();
    private final DateFormat DATA = new SimpleDateFormat("yyyy-MM-dd");
    private Date data;
    private DeliveryDAO deliveryDAO = new DeliveryDAO();
    private ConexaoBanco conexao = new ConexaoBanco();
   
    
    /**
     * Creates new form FormVendaDelivery
     */
    public FormVendaDelivery() {
        
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        inicializarTabela();
        carregarTabela();
        txt_telefone.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lbSair4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_icone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSair = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbSair2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_observacao = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_descricao = new javax.swing.JTextField();
        txt_quantidade = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_buscaNome = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txt_opcional = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_precoOpcional = new javax.swing.JTextField();
        bt_calcularOpcional = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_incluir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbSair6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_taxa = new javax.swing.JTextField();
        bt_salvar = new javax.swing.JButton();
        txt_sair = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_icone1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();

        jPanel5.setBackground(new java.awt.Color(170, 169, 149));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbSair4.setToolTipText("");
        lbSair4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSair4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel16)
                .addGap(81, 81, 81)
                .addComponent(lbSair4)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lbSair4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pedidos Delivery");

        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esfihas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_icone)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbSair)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_icone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lbSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 940, 110));

        jPanel3.setBackground(new java.awt.Color(170, 169, 149));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbSair2.setToolTipText("");
        lbSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSair2MouseClicked(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Cliente"));

        jLabel1.setText("TELEFONE:");

        txt_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_telefoneKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jLabel3.setToolTipText("Cadastrar Cliente");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        txt_observacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_observacaoKeyPressed(evt);
            }
        });

        jLabel24.setText("OBSERVAÇÃO:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_observacao)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Descrição", "Quant", "Preço", "Total", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela.setAutoscrolls(false);
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Produto"));

        jLabel8.setText("CÓDIGO:");

        jLabel9.setText("DESCRIÇÃO:");

        jLabel10.setText("QUANT:");

        jLabel11.setText("PREÇO:");

        txt_codigo.setEnabled(false);
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codigoKeyReleased(evt);
            }
        });

        txt_descricao.setEditable(false);
        txt_descricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descricaoKeyPressed(evt);
            }
        });

        txt_quantidade.setEnabled(false);
        txt_quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_quantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantidadeKeyReleased(evt);
            }
        });

        txt_preco.setEditable(false);
        txt_preco.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel13.setText("TOTAL:");

        txt_total.setEditable(false);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txt_buscaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscaNomeFocusLost(evt);
            }
        });
        txt_buscaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscaNomeKeyReleased(evt);
            }
        });

        jLabel28.setText("NOME:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opcionais"));

        txt_opcional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_opcionalKeyPressed(evt);
            }
        });

        jLabel19.setText("Opcionais R$:");

        txt_precoOpcional.setEnabled(false);
        txt_precoOpcional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_precoOpcionalKeyPressed(evt);
            }
        });

        bt_calcularOpcional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator.png"))); // NOI18N
        bt_calcularOpcional.setText("Calcular");
        bt_calcularOpcional.setEnabled(false);
        bt_calcularOpcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularOpcionalActionPerformed(evt);
            }
        });
        bt_calcularOpcional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_calcularOpcionalKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_opcional, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_precoOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_calcularOpcional)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(txt_opcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precoOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_calcularOpcional)
                    .addComponent(jLabel19)))
        );

        bt_excluir.setBackground(new java.awt.Color(170, 169, 149));
        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eraser.png"))); // NOI18N
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_incluir.setBackground(new java.awt.Color(170, 169, 149));
        bt_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus(1).png"))); // NOI18N
        bt_incluir.setText("Incluir");
        bt_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incluirActionPerformed(evt);
            }
        });
        bt_incluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_incluirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_incluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(lbSair2)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_incluir))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_excluir)
                        .addGap(65, 65, 65)
                        .addComponent(lbSair2))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 930, 390));

        jPanel7.setBackground(new java.awt.Color(170, 169, 149));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel7.setLayout(null);

        lbSair6.setToolTipText("");
        lbSair6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSair6MouseClicked(evt);
            }
        });
        jPanel7.add(lbSair6);
        lbSair6.setBounds(692, 149, 0, 0);
        jPanel7.add(jLabel18);
        jLabel18.setBounds(459, 1, 0, 148);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Entrega"));

        jLabel5.setText("NOME:");

        jLabel6.setText("ENDEREÇO:");

        jLabel7.setText("BAIRRO:");

        txt_nome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nome.setEnabled(false);

        txt_endereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_endereco.setEnabled(false);

        txt_bairro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_bairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_bairro.setEnabled(false);

        jLabel23.setText("TAXA R$");

        txt_taxa.setEditable(false);
        txt_taxa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_taxa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_taxa.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_taxa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txt_taxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel7.add(jPanel2);
        jPanel2.setBounds(10, 10, 480, 110);

        bt_salvar.setBackground(new java.awt.Color(170, 169, 149));
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok.png"))); // NOI18N
        bt_salvar.setText("Confirmar");
        bt_salvar.setEnabled(false);
        bt_salvar.setHideActionText(true);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        jPanel7.add(bt_salvar);
        bt_salvar.setBounds(770, 10, 140, 41);

        txt_sair.setBackground(new java.awt.Color(170, 169, 149));
        txt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel.png"))); // NOI18N
        txt_sair.setText("Cancelar");
        txt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sairActionPerformed(evt);
            }
        });
        jPanel7.add(txt_sair);
        txt_sair.setBounds(770, 70, 140, 41);

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("TOTAL:");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(520, 20, 68, 22);

        lbl_total.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 0, 0));
        lbl_total.setText("0,00");
        jPanel7.add(lbl_total);
        lbl_total.setBounds(580, 40, 180, 60);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 930, 130));

        jPanel6.setBackground(new java.awt.Color(170, 169, 149));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CARDÁPIO DE PRODUTOS");

        jScrollPane2.setBackground(new java.awt.Color(170, 169, 149));

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_produtosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_produtos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(lbl_icone1))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_icone1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked

    }//GEN-LAST:event_lbSairMouseClicked

    private void lbSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSair2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSair2MouseClicked

    private void lbSair4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSair4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSair4MouseClicked

    private void lbSair6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSair6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSair6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         if (formCli == null){
            formCli = new FormClientes();
        }
        //formCli.setModal(true);
        formCli.setVisible(true);
        formCli.setAlwaysOnTop(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_telefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefoneKeyReleased
        // TODO add your handling code here:
         if (!txt_telefone.getText().equals("")) {
            if (numeros.contains(evt.getKeyChar() + "")) {

                cliente.setTelefone(txt_telefone.getText());

                if (clienteDAO.buscaCliente(cliente)) {
                    txt_nome.setText(cliente.getNome());
                    txt_endereco.setText(cliente.getEndereco()+" Nº: "+cliente.getNumero()+"  "+cliente.getComplemento());
                    txt_bairro.setText(cliente.getBairro());
                    bt_salvar.setEnabled(true);
                    txt_taxa.setText(decimal.format(cliente.getPreco_entrega()));
                    //idcliente = c.getIdCliente();
                } else {
                    txt_nome.setText("Cliente Não Localizado!");
                    bt_salvar.setEnabled(false);
                }
            }
        } else {
            txt_nome.setText("");
            txt_endereco.setText("");
            txt_bairro.setText("");
            bt_salvar.setEnabled(false);
        }
    }//GEN-LAST:event_txt_telefoneKeyReleased

    private void txt_codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyReleased
        // TODO add your handling code here:
         if (!txt_codigo.getText().equals("")) {
            if (numeros.contains(evt.getKeyChar() + "")) {

                produto.setCodigo(Integer.parseInt(txt_codigo.getText()));

                if (produtoDAO.buscaProduto(produto)) {
                    txt_descricao.setText(produto.getDescrição());
                    txt_preco.setText(decimal.format(produto.getPreco()));
                    
                    //btSalvar.setEnabled(true);
                    //idcliente = c.getIdCliente();
                } else {
                    txt_descricao.setText("Produto Não Localizado!");
                    //btSalvar.setEnabled(false);
                }
            }
        } else {
           txt_descricao.setText("");
           txt_preco.setText("");
           txt_quantidade.setText("");
           txt_total.setText("");
        }
    }//GEN-LAST:event_txt_codigoKeyReleased

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == 10){
           txt_quantidade.setEnabled(true);
           txt_quantidade.requestFocus();
         } 
         
      
        
    }//GEN-LAST:event_txt_codigoKeyPressed

    private void txt_quantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantidadeKeyPressed
       if (evt.getKeyCode() == 10){
           bt_incluir.requestFocus();
       }
    }//GEN-LAST:event_txt_quantidadeKeyPressed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_quantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantidadeKeyReleased
        if (!txt_quantidade.getText().equals("")) {
            if (numeros.contains(evt.getKeyChar() + "")) {

                double soma = Double.parseDouble(txt_quantidade.getText().replaceAll(",", ".")) 
                        * Double.parseDouble(txt_preco.getText().replaceAll(",", "."));
               
                txt_total.setText(decimal.format(soma));
                    
                    //btSalvar.setEnabled(true);
                    //idcliente = c.getIdCliente();
               
            }
        } else {
            txt_total.setText("");
        }
    }//GEN-LAST:event_txt_quantidadeKeyReleased

    private void bt_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incluirActionPerformed
        // TODO add your handling code here:
        insereTabela();
        txt_codigo.requestFocus();
        
    }//GEN-LAST:event_bt_incluirActionPerformed
    public void atualizaTotal() {
        double aux = 0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            aux += Double.valueOf(String.valueOf(tabela.getValueAt(i, 4)).replace(",", "."));
        }
        lbl_total.setText(decimal.format(aux));
    }
    public void limparProdutos(){
        txt_codigo.setText("");
        txt_descricao.setText("");
        txt_quantidade.setText("");
        txt_preco.setText("");
        txt_total.setText("");
        txt_opcional.setText("");
        txt_precoOpcional.setText("");
   }
    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        // TODO add your handling code here:
         if (tabela.getSelectedRow() > -1){
            if (JOptionPane.showConfirmDialog(this, "Deseja Excluir o Produto Selecionado?","Gold Food",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                tabelaAux.removeRow(tabela.getSelectedRow());
                atualizaTotal();
            }
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_incluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_incluirKeyPressed
        insereTabela();
        txt_codigo.requestFocus();
    }//GEN-LAST:event_bt_incluirKeyPressed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        FormPagamentoDelivery frPagamento = new FormPagamentoDelivery(this);
        PreencheClasse();
        
        frPagamento.itensVenda(delivery,"cadastrar");
      
        frPagamento.setVisible(true);
        frPagamento.setAlwaysOnTop(true);

//       salvar();
//       limpar();
//       this.dispose();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_calcularOpcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularOpcionalActionPerformed
        calcularOpcional();
    }//GEN-LAST:event_bt_calcularOpcionalActionPerformed
    public void calcularOpcional(){
        if(!txt_total.getText().isEmpty() && !txt_opcional.getText().isEmpty()){
             double soma = Double.parseDouble(txt_total.getText().replaceAll(",", ".")) + 
                        Double.parseDouble(txt_precoOpcional.getText().replaceAll(",", "."));
               
              txt_total.setText(decimal.format(soma));
              txt_precoOpcional.setText("");
       }else{
           JOptionPane.showMessageDialog(null, "Preencha o produto antes de preencher o opcional!");
       }
    }
    private void txt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sairActionPerformed
        sair();
    }//GEN-LAST:event_txt_sairActionPerformed
    public void sair(){
          this.dispose();
          limpar();
    }
    private void tabela_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_produtosMouseClicked
        // TODO add your handling code here:
        String id = ""+tabela_produtos.getValueAt(tabela_produtos.getSelectedRow(), 0);
        conexao.conecta();
       
        conexao.executaSQL("select * from tb_produtos where codigo_produto = '"+id +"'");
      
        try {
            conexao.rs.first();
            txt_codigo.setText(String.valueOf(conexao.rs.getInt("codigo_produto")));
            txt_descricao.setText(conexao.rs.getString("descricao"));
            txt_preco.setText(String.valueOf(conexao.rs.getDouble("preco")));
                        
            txt_quantidade.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(FormVendaDelivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabela_produtosMouseClicked

    private void txt_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10){
        txt_codigo.setEnabled(true);
        txt_codigo.requestFocus();
        }
    }//GEN-LAST:event_txt_telefoneKeyPressed

    private void txt_observacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_observacaoKeyPressed
        if (evt.getKeyCode() == 10){
        txt_codigo.setEnabled(true);
        txt_codigo.requestFocus();
        }
    }//GEN-LAST:event_txt_observacaoKeyPressed

    private void txt_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descricaoKeyPressed
          if (!txt_codigo.getText().equals("")) {
            if (numeros.contains(evt.getKeyChar() + "")) {

                produto.setCodigo(Integer.parseInt(txt_codigo.getText()));

                if (produtoDAO.buscaProduto(produto)) {
                    txt_descricao.setText(produto.getDescrição());
                    txt_preco.setText(decimal.format(produto.getPreco()));
                    
                    //btSalvar.setEnabled(true);
                    //idcliente = c.getIdCliente();
                } else {
                    txt_descricao.setText("Produto Não Localizado!");
                    //btSalvar.setEnabled(false);
                }
            }
        } else {
           txt_descricao.setText("");
           txt_preco.setText("");
           txt_quantidade.setText("");
           txt_total.setText("");
        }
    }//GEN-LAST:event_txt_descricaoKeyPressed

    private void txt_opcionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_opcionalKeyPressed
        if (evt.getKeyCode() == 10){
        bt_calcularOpcional.setEnabled(true);    
        txt_precoOpcional.setEnabled(true);
        txt_precoOpcional.requestFocus();
    
        }
    }//GEN-LAST:event_txt_opcionalKeyPressed

    private void txt_precoOpcionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precoOpcionalKeyPressed
       if (evt.getKeyCode() == 10){
          bt_calcularOpcional.requestFocus();
    
        }
    }//GEN-LAST:event_txt_precoOpcionalKeyPressed

    private void bt_calcularOpcionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_calcularOpcionalKeyPressed
        calcularOpcional();
        bt_incluir.requestFocus();
    }//GEN-LAST:event_bt_calcularOpcionalKeyPressed

    private void txt_buscaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscaNomeKeyReleased
        String pesquisa = txt_buscaNome.getText();
             listarTabela("Select * from tb_produtos where descricao LIKE '%"+pesquisa+"%'");
    }//GEN-LAST:event_txt_buscaNomeKeyReleased

    private void txt_buscaNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaNomeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscaNomeFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        carregarTabela();
    }//GEN-LAST:event_formWindowGainedFocus
        public void insereTabela() {
         if (!txt_total.getText().equals("")) {
            if (linhas == null) {
                linhas = new Object[6];
            }

            linhas[0] = txt_codigo.getText();
            linhas[1] = txt_descricao.getText();
            linhas[2] = txt_quantidade.getText();
            linhas[3] = txt_preco.getText();
            linhas[4] = txt_total.getText();
            linhas[5] = txt_opcional.getText();

            tabelaAux = (DefaultTableModel) tabela.getModel();
            tabelaAux.insertRow(tabelaAux.getRowCount(), linhas);

            atualizaTotal();
            limparProdutos();
            txt_quantidade.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insira os Dados Corretamente!", "Gold Food", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public void inicializarTabela(){
         tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
         tabela.getColumnModel().getColumn(0).setResizable(false);
         tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
         tabela.getColumnModel().getColumn(1).setResizable(false);
         tabela.getColumnModel().getColumn(2).setPreferredWidth(50);
         tabela.getColumnModel().getColumn(2).setResizable(false);
         tabela.getColumnModel().getColumn(3).setPreferredWidth(50);
         tabela.getColumnModel().getColumn(3).setResizable(false);
         tabela.getColumnModel().getColumn(4).setPreferredWidth(50);
         tabela.getColumnModel().getColumn(4).setResizable(false);
         tabela.getColumnModel().getColumn(5).setPreferredWidth(200);
         tabela.getColumnModel().getColumn(5).setResizable(false);
        
    }
    public void carregarTabela(){
        listarTabela("SELECT * FROM tb_produtos");
    }
    public void listarTabela(String sql){
        
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código","Referência","Descrição","Preço"};
        conexao.conecta();
        conexao.executaSQL(sql);
        
               
        try {
            conexao.rs.first();
            do{
                dados.add(new Object[]{
                                                       conexao.rs.getInt("codigo_produto"),
                                                       conexao.rs.getString("referencia"),
                                                       conexao.rs.getString("descricao"),
                                                       decimal.format(conexao.rs.getDouble("preco")),
                                                       });
            
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            System.out.println("Erro ao Preencher a Tabela"+ ex);
        }
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabela_produtos.setModel(modelo);
         tabela_produtos.getColumnModel().getColumn(0).setPreferredWidth(50);
         tabela_produtos.getColumnModel().getColumn(0).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(1).setPreferredWidth(50);
         tabela_produtos.getColumnModel().getColumn(1).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(2).setPreferredWidth(230);
         tabela_produtos.getColumnModel().getColumn(2).setResizable(false);
         tabela_produtos.getColumnModel().getColumn(3).setPreferredWidth(50);
         tabela_produtos.getColumnModel().getColumn(3).setResizable(false);
                             
         tabela_produtos.getTableHeader().setReorderingAllowed(false);
         tabela_produtos.setAutoResizeMode( tabela_produtos.AUTO_RESIZE_OFF);
         tabela_produtos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
       
     }
     public void PreencheClasse() {

        if (delivery == null) {
            delivery = new Delivery();
           
        }
        
        delivery.setIdCliente(cliente);
        delivery.setTotalPedido(Float.valueOf(lbl_total.getText().replaceAll(",", ".")));
        delivery.setItensDelivery(tabelaAux);
        delivery.setDataVenda(retornaData());
        delivery.setStatus("ABERTO");
        delivery.setObservacao(txt_observacao.getText());
        delivery.setEntrega(Float.parseFloat(txt_taxa.getText().replaceAll(",", ".")));
               
        }
    public void salvar(){
        if (txt_nome.getText().equals("") || txt_telefone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preenche todos os campos",
                    "Delivery", JOptionPane.WARNING_MESSAGE);
        } else {
            PreencheClasse();
            deliveryDAO.cadastraVendaDelivery(delivery);
            //limpaformulario();
            
            JOptionPane.showMessageDialog(this, "Pedido registrado!",
                    "Delivery", JOptionPane.INFORMATION_MESSAGE);
        }
    } 
    public void limpar(){
        limparProdutos();
        txt_telefone.setText("");
        txt_observacao.setText("");
        txt_nome.setText("");
        txt_endereco.setText("");
        txt_taxa.setText("");
       
        txt_bairro.setText("");
       
        lbl_total.setText("0,00");
       
        while (tabela.getRowCount() > 0) {
            ((DefaultTableModel) tabela.getModel()).removeRow(0);
        }
    }
    public String retornaData() {
        data = new Date();
        String aux = DATA.format(data);
        return aux;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendaDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendaDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendaDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendaDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendaDelivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcularOpcional;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_incluir;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbSair;
    private javax.swing.JLabel lbSair2;
    private javax.swing.JLabel lbSair4;
    private javax.swing.JLabel lbSair6;
    private javax.swing.JLabel lbl_icone;
    private javax.swing.JLabel lbl_icone1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela_produtos;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_buscaNome;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_observacao;
    private javax.swing.JTextField txt_opcional;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_precoOpcional;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JButton txt_sair;
    private javax.swing.JTextField txt_taxa;
    private javax.swing.JTextField txt_telefone;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
