/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.DeliveryDAO;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Delivery;

/**
 *
 * @author Aluno
 */
public class FormPagamentoDelivery extends javax.swing.JDialog {
    public double totalProdutos, entrega, total, dinheiro , cartao, troco ;
    private final String numeros = "0123456789";
    private double venda;
    private double taxaEntrega;
    private Delivery delivery;
    private final DeliveryDAO deliveryDAO = new DeliveryDAO();
    private JFrame frame = new JFrame();
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private String tipo, mensagem;
    /**
     * Creates new form FormCupom
     * @param fr
     */
    public FormPagamentoDelivery(JFrame fr) {
        super(fr);
       
        initComponents();
        frame = fr;
        
        
       
       
    }
    public void itensVenda(Delivery del, String msg){
        mensagem = msg;
        delivery = del;
        venda = delivery.getTotalPedido();
        taxaEntrega = delivery.getEntrega();
        
        txt_entrega.setText(decimal.format(taxaEntrega));
        lbl_totalProdutos.setText(decimal.format(venda));
        carregarComponentes();
        
        txt_dinheiro.setText(decimal.format(total));
        txt_dinheiro.requestFocus();
        txt_dinheiro.selectAll();
       
        System.out.println(mensagem); 
    }

    private FormPagamentoDelivery() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void carregarComponentes(){
        tipo = (String)cb_tipo.getSelectedItem();
        totalProdutos = Double.parseDouble(lbl_totalProdutos.getText().replaceAll(",", "."));
        if(!txt_entrega.getText().isEmpty()){
            taxaEntrega = Double.parseDouble(txt_entrega.getText().replaceAll(",", "."));
            if(!txt_dinheiro.getText().isEmpty()){
                 dinheiro = Double.parseDouble(txt_dinheiro.getText().replaceAll(",", "."));
                 if(!txt_cartão.getText().isEmpty()){
                     cartao = Double.parseDouble(txt_cartão.getText().replaceAll(",", "."));
                    
                 }else{
                     cartao = 0.00;
                 }
            }else{
                dinheiro = 0.00;
            }
        }else{
            taxaEntrega = 0.00;
        }
        
        total = totalProdutos+taxaEntrega;
        lbl_total.setText(decimal.format(total));
        
       
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_entrega = new javax.swing.JTextField();
        txt_dinheiro = new javax.swing.JTextField();
        txt_cartão = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_totalProdutos = new javax.swing.JLabel();
        lbl_falta = new javax.swing.JLabel();
        lbl_troco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_valorTotal = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("DINHEIRO:");

        jLabel5.setText("CARTÃO:");

        jLabel6.setText("ENTREGA:");

        txt_entrega.setText("0,00");
        txt_entrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_entregaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_entregaKeyReleased(evt);
            }
        });

        txt_dinheiro.setText("0,00");
        txt_dinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dinheiroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dinheiroKeyReleased(evt);
            }
        });

        txt_cartão.setText("0,00");
        txt_cartão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cartãoActionPerformed(evt);
            }
        });
        txt_cartão.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cartãoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cartãoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("TOTAL PRODUTOS R$");

        lbl_totalProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalProdutos.setText("0,00");

        lbl_falta.setText("TROCO R$");

        lbl_troco.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_troco.setText("0,00");

        jLabel2.setText("Total:");

        lbl_valorTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_valorTotal.setForeground(new java.awt.Color(255, 0, 0));
        lbl_valorTotal.setText("0,00");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega", "vem Buscar", "Venda no Balcão" }));
        cb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoActionPerformed(evt);
            }
        });

        jLabel12.setText("VALOR TOTAL R$");

        lbl_total.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_total.setText("0,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbl_falta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_totalProdutos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_cartão, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(txt_dinheiro)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_totalProdutos))
                .addGap(13, 13, 13)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cartão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_falta)
                    .addComponent(lbl_troco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_valorTotal)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6))
        );

        jButton1.setBackground(new java.awt.Color(170, 169, 149));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bt_salvar.setBackground(new java.awt.Color(170, 169, 149));
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        bt_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_salvarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAGAMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)))
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bt_salvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dinheiroKeyReleased
        // TODO add your handling code here:
            if (!txt_dinheiro.getText().equals("")){
               if (numeros.contains(evt.getKeyChar() + "")) {
                   carregarComponentes();
                   calcular();
                   calcularTroco();
                   
               }
            }else{
                carregarComponentes();
                calcular();
                calcularTroco();
               
            }
    }//GEN-LAST:event_txt_dinheiroKeyReleased

    private void txt_cartãoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cartãoKeyReleased
        // TODO add your handling code here:
            if (!txt_cartão.getText().equals("")){
               if (numeros.contains(evt.getKeyChar() + "")) {
                  carregarComponentes();
                  calcular();
                  calcularTroco();
                  
               }
            }else{
                carregarComponentes();
                calcular();
                calcularTroco();
                
            }
            
    }//GEN-LAST:event_txt_cartãoKeyReleased

    private void txt_entregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entregaKeyReleased
        // TODO add your handling code here:
         if (numeros.contains(evt.getKeyChar() + "")) {
          if (!txt_entrega.getText().equals("")){
               if (numeros.contains(evt.getKeyChar() + "")) {
                  carregarComponentes();
                  calcular();
                  
               }
            }else{
                carregarComponentes();
                calcular();
              
           
            }
       }
    }//GEN-LAST:event_txt_entregaKeyReleased
  public void calcular(){
        carregarComponentes();
        double aux = 0;
        aux += dinheiro + cartao;
        lbl_valorTotal.setText(decimal.format(aux));
       
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
       if(mensagem.equals("cadastrar")){
           
        salvar();
       }if(mensagem.equals("alterar")){
           alterar();
       }
       
        
        System.out.println(mensagem); 
        
    }//GEN-LAST:event_bt_salvarActionPerformed
    public void salvar(){
        carregarDelivery();
        deliveryDAO.cadastraVendaDelivery(delivery);
        JOptionPane.showMessageDialog(this, "Pedido Cadastrado!");
        frame.dispose();
        this.dispose();
    }
    public void alterar(){
        carregarDelivery();
        delivery.setStatus("FECHADO");
        deliveryDAO.alterarDelivery(delivery);
        
        JOptionPane.showMessageDialog(this, "Pedido Alterado!");
        this.dispose();
    }
    public void carregarDelivery(){
        delivery.setEntrega(Float.parseFloat(txt_entrega.getText().replaceAll(",", ".")));
        delivery.setTotalPedido(Float.parseFloat(lbl_valorTotal.getText().replaceAll(",", ".")));
        delivery.setTroco(Float.parseFloat(lbl_troco.getText().replaceAll(",", ".")));
        delivery.setCartao(Float.parseFloat(txt_cartão.getText().replace(",", ".")));
        delivery.setDinheiro(Float.parseFloat(txt_dinheiro.getText().replaceAll(",", ".")));
        delivery.setTipo((String)cb_tipo.getSelectedItem());
    }
    private void cb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoActionPerformed
        carregarComponentes();
        if(!tipo.equals("Entrega")){
            double entrega = Double.parseDouble(txt_entrega.getText().replaceAll(",", "."));
            double dinheiro = Double.parseDouble(txt_dinheiro.getText().replaceAll(",", "."));
            txt_dinheiro.setText(decimal.format(dinheiro - entrega));
            txt_entrega.setText("0,00");
            txt_entrega.setEnabled(false);
            calcular();
            
           
        }else{
            txt_entrega.setEnabled(true);
        }
  
    }//GEN-LAST:event_cb_tipoActionPerformed

    private void txt_dinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dinheiroKeyPressed
        if (evt.getKeyCode() == 10){
           calcular();
           
           txt_cartão.requestFocus();
           txt_cartão.selectAll();
        }
    }//GEN-LAST:event_txt_dinheiroKeyPressed

    private void txt_cartãoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cartãoKeyPressed
        if (evt.getKeyCode() == 10){
           
           bt_salvar.requestFocus();
           
        }
    }//GEN-LAST:event_txt_cartãoKeyPressed

    private void txt_entregaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entregaKeyPressed
        if (evt.getKeyCode() == 10){
           txt_dinheiro.requestFocus();
           txt_dinheiro.selectAll();
        }
    }//GEN-LAST:event_txt_entregaKeyPressed

    private void bt_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_salvarKeyPressed
       if (evt.getKeyCode() == 10){
            if(mensagem.equals("cadastrar")){
           
        salvar();
       }if(mensagem.equals("alterar")){
           alterar();
       }
        }
    }//GEN-LAST:event_bt_salvarKeyPressed

    private void txt_cartãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cartãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cartãoActionPerformed

        
    public void calcularTroco(){
                       
            troco = dinheiro - Double.parseDouble(lbl_total.getText().replaceAll(",", "."));
            
            troco += cartao;
            
            lbl_troco.setText(decimal.format(troco));
            if(troco < 0){
                lbl_falta.setText("FALTA R$ ");
                lbl_falta.setForeground(Color.RED);
            }else{
                lbl_falta.setText("TROCO RS ");
                lbl_falta.setForeground(Color.BLUE);
            }
             
            
    }
    
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagamentoDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPagamentoDelivery().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salvar;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_falta;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_totalProdutos;
    private javax.swing.JLabel lbl_troco;
    private javax.swing.JLabel lbl_valorTotal;
    private javax.swing.JTextField txt_cartão;
    private javax.swing.JTextField txt_dinheiro;
    private javax.swing.JTextField txt_entrega;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the venda
     */
    public double getVenda() {
        return venda;
    }

    /**
     * @param venda the venda to set
     */
    public void setVenda(double venda) {
        this.venda = venda;
    }

    /**
     * @return the taxaEntrega
     */
    public double getTaxaEntrega() {
        return taxaEntrega;
    }

    /**
     * @param taxaEntrega the taxaEntrega to set
     */
    public void setTaxaEntrega(double taxaEntrega) {
        this.taxaEntrega = taxaEntrega;
    }
    
     
}
