/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ClientesDAO;
import correios.BuscarCep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Cliente;
import util.ConexaoBanco;
import util.ModeloTabela;
import util.UpperCaseField;

/**
 *
 * @author Escritorio
 */
public class FormClientes extends javax.swing.JFrame {
    private Cliente cliente = new Cliente();
    private final ClientesDAO cDAO = new ClientesDAO();
    private final BuscarCep buscarCep = new BuscarCep();
    private final ConexaoBanco conexao = new ConexaoBanco();
    private FormBairros frmBairro;
    /** Creates new form formDelivery */
    public FormClientes() {
        initComponents();
        listarTabela();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_icone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSair = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nome = new UpperCaseField();
        txt_endereco = new UpperCaseField();
        txt_numero = new javax.swing.JTextField();
        txt_complemento = new UpperCaseField();
        txt_telefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_bairros = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JFormattedTextField();
        bt_buscarCep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Clientes");

        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esfihas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addGap(81, 81, 81)
                        .addComponent(lbSair)
                        .addGap(483, 483, 483))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_icone)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_icone)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TELEFONE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("END:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nº");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("COMP:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("BAIRRO");

        txt_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nome.setEnabled(false);
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomeKeyPressed(evt);
            }
        });

        txt_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_endereco.setEnabled(false);
        txt_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_enderecoKeyPressed(evt);
            }
        });

        txt_numero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_numero.setEnabled(false);
        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numeroKeyPressed(evt);
            }
        });

        txt_complemento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_complemento.setEnabled(false);
        txt_complemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_complementoKeyPressed(evt);
            }
        });

        txt_telefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_telefone.setEnabled(false);
        txt_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefoneKeyPressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus.png"))); // NOI18N
        jLabel9.setText("Cadastrar Bairro");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        cb_bairros.setEnabled(false);
        cb_bairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bairrosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CEP:");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cep.setEnabled(false);

        bt_buscarCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search(1).png"))); // NOI18N
        bt_buscarCep.setEnabled(false);
        bt_buscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_buscarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_bairros, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt_buscarCep)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_bairros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        bt_novo.setBackground(new java.awt.Color(170, 169, 149));
        bt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        bt_novo.setText("NOVO");
        bt_novo.setToolTipText("");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setBackground(new java.awt.Color(170, 169, 149));
        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        bt_salvar.setText("SALVAR");
        bt_salvar.setToolTipText("");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        bt_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_salvarKeyPressed(evt);
            }
        });

        bt_editar.setBackground(new java.awt.Color(170, 169, 149));
        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit_text.png"))); // NOI18N
        bt_editar.setText("EDITAR");
        bt_editar.setToolTipText("");
        bt_editar.setEnabled(false);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setBackground(new java.awt.Color(170, 169, 149));
        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eraser.png"))); // NOI18N
        bt_excluir.setText("EXCLUIR");
        bt_excluir.setToolTipText("");
        bt_excluir.setEnabled(false);
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_sair.setBackground(new java.awt.Color(170, 169, 149));
        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        bt_sair.setText("SAIR");
        bt_sair.setToolTipText("");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluir)
                    .addComponent(bt_editar)
                    .addComponent(bt_salvar)
                    .addComponent(bt_novo)
                    .addComponent(bt_sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked
        
    }//GEN-LAST:event_lbSairMouseClicked

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        //sair da tela
        bt_novo.setEnabled(true);
        limparComponentes();
        desativarComponentes();
        this.dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
         // funcão do botão salvar
        salvar();
        desativarComponentes();
        limparComponentes();
        listarTabela();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        // Funcão do botão excluir
         String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
         if (JOptionPane.showConfirmDialog(this, "Deseja Excluir o cliente Selecionado?","Gold Food",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){  
            try {
                    conexao.conecta();

                    conexao.executaSQL("select * from tb_clientes where codigo_cliente = '"+id +"'");
                    conexao.rs.first();
                    cliente.setCodigo(conexao.rs.getInt("codigo_cliente"));
                    cDAO.excluirClientes(cliente);
                    JOptionPane.showMessageDialog(this, "Cliente Excluido!");

                    listarTabela();


                } catch (SQLException ex) {
                    Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
         }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
         //Carregar os componentes quanto clicar na linha da tabela
        ativarComponentes();
        cb_bairros.removeAllItems();
        String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
        conexao.conecta();
        
        conexao.executaSQL("select * from tb_clientes where codigo_cliente = '"+id +"'");
        bt_editar.setEnabled(true);
        bt_excluir.setEnabled(true);
        try {
            conexao.rs.first();
            txt_nome.setText(conexao.rs.getString("nome"));
            txt_endereco.setText(conexao.rs.getString("endereco"));
            txt_numero.setText(String.valueOf(conexao.rs.getInt("numero")));
            txt_complemento.setText(conexao.rs.getString("complemento"));
            cb_bairros.addItem(String.valueOf(conexao.rs.getString("bairro")));
            txt_telefone.setText(conexao.rs.getString("telefone"));

            
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
           // evento para botão alterar
         String id = ""+tabela.getValueAt(tabela.getSelectedRow(), 0);
                         
    try {
            conexao.conecta();
            conexao.executaSQL("select * from tb_clientes where codigo_cliente = '"+id +"'");
            conexao.rs.first();
            cliente = new Cliente();
            
            cliente.setCodigo(conexao.rs.getInt("codigo_cliente"));
            cliente.setNome(txt_nome.getText());
            cliente.setEndereco(txt_endereco.getText());
            cliente.setNumero(Integer.parseInt(txt_numero.getText()));
            cliente.setComplemento(txt_complemento.getText());
            cliente.setBairro((String)cb_bairros.getSelectedItem());
            cliente.setTelefone(txt_telefone.getText());
            cDAO.alterarClientes(cliente);
            
            JOptionPane.showMessageDialog(this, "Cliente Alterado!");
            
            listarTabela();
            
        } catch (SQLException ex) {
            Logger.getLogger(FormProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
       desativarComponentes();
       limparComponentes();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        //função do botão novo
        limparComponentes();
        ativarComponentes();
        txt_nome.requestFocus();
        bt_novo.setEnabled(false);
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(false);
        bt_excluir.setEnabled(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void txt_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyPressed
         if (evt.getKeyCode() == 10){
           txt_telefone.requestFocus();
        }
    }//GEN-LAST:event_txt_nomeKeyPressed

    private void txt_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefoneKeyPressed
        if (evt.getKeyCode() == 10){
           txt_endereco.requestFocus();
        }
    }//GEN-LAST:event_txt_telefoneKeyPressed

    private void txt_enderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enderecoKeyPressed
        if (evt.getKeyCode() == 10){
           txt_numero.requestFocus();
        }
    }//GEN-LAST:event_txt_enderecoKeyPressed

    private void txt_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyPressed
       if (evt.getKeyCode() == 10){
           txt_complemento.requestFocus();
        }
    }//GEN-LAST:event_txt_numeroKeyPressed

    private void txt_complementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_complementoKeyPressed
        if (evt.getKeyCode() == 10){
           //txt_bairro.requestFocus();
        }
    }//GEN-LAST:event_txt_complementoKeyPressed

    private void bt_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_salvarKeyPressed
        if (evt.getKeyCode() == 10){
           salvar();
        }
    }//GEN-LAST:event_bt_salvarKeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         if (frmBairro == null){
            frmBairro = new FormBairros(this, rootPaneCheckingEnabled);
        }
        frmBairro.setModal(true);
        frmBairro.setVisible(true);
       
    }//GEN-LAST:event_jLabel9MouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        listarBairros();
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        listarBairros();
    }//GEN-LAST:event_formWindowGainedFocus

    private void bt_buscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarCepActionPerformed
        String aux = txt_cep.getText();
        cliente = buscarCep.buscarCep(aux);
        txt_endereco.setText(cliente.getEndereco());
        boolean testar = testarBairro(cliente.getBairro());
        if(testar == false){
            FormBairros bairro = new FormBairros(this, true);
            bairro.carregarBairro(cliente.getBairro());
            bairro.setVisible(true);
            
        }
    }//GEN-LAST:event_bt_buscarCepActionPerformed
    public Boolean testarBairro(String bairro){
        boolean teste = true;
        conexao.conecta();
        conexao.executaSQL("SELECT * FROM tb_bairros where nome_bairro = '"+bairro+"'");
        try {
            if(!conexao.rs.first()){
                teste = false;
            }
                 
        } catch (SQLException ex) {
            Logger.getLogger(FormClientes.class.getName()).log(Level.SEVERE, null, ex);
          
        }
        conexao.Desconecta();
        return teste;
    }
    private void cb_bairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bairrosActionPerformed

    }//GEN-LAST:event_cb_bairrosActionPerformed
     
    public void salvar(){
        if(!txt_nome.getText().isEmpty()|| !txt_telefone.getText().isEmpty()
                || !txt_endereco.getText().isEmpty()){
             cliente = new Cliente();
             cliente.setNome(txt_nome.getText());
             cliente.setTelefone(txt_telefone.getText());
             cliente.setEndereco(txt_endereco.getText());
             cliente.setNumero(Integer.parseInt(txt_numero.getText()));
             cliente.setComplemento(txt_complemento.getText());
             cliente.setBairro(String.valueOf(cb_bairros.getSelectedItem()));
             cDAO.SalvarClientes(cliente);
             
             JOptionPane.showMessageDialog(this, "Cliente Salvo com Sucesso!");
             listarTabela();
             limparComponentes();
        }else{
            JOptionPane.showMessageDialog(this, "Preenche os campos Descrição e Preço");
        }
        bt_novo.setEnabled(true);
        bt_salvar.setEnabled(false);
    }
     public final void listarTabela(){
        String sql = "SELECT * FROM tb_clientes";
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código","Nome","Telefone","Endereço"};
        conexao.conecta();
        conexao.executaSQL(sql);
        
               
        try {
            conexao.rs.first();
            do{
                dados.add(new Object[]{
                                                       conexao.rs.getInt("codigo_cliente"),
                                                       conexao.rs.getString("nome"),
                                                       conexao.rs.getString("telefone"),
                                                       conexao.rs.getString("endereco")
                                                               +" nº "+
                                                       conexao.rs.getString("numero")
                                                               +" - "+
                                                       conexao.rs.getString("bairro"),
                                                       });
            
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            System.out.println("Erro ao Preencher a Tabela"+ ex);
        }
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabela.setModel(modelo);
         tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
         tabela.getColumnModel().getColumn(0).setResizable(false);
         tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
         tabela.getColumnModel().getColumn(1).setResizable(false);
         tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
         tabela.getColumnModel().getColumn(2).setResizable(false);
         tabela.getColumnModel().getColumn(3).setPreferredWidth(400);
         tabela.getColumnModel().getColumn(3).setResizable(false);
                             
         tabela.getTableHeader().setReorderingAllowed(false);
         tabela.setAutoResizeMode( tabela.AUTO_RESIZE_OFF);
         tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
       
     }
      public ResultSet listarBairros(){
        
        cb_bairros.removeAllItems();
        
        conexao.conecta();
        conexao.executaSQL("select * from tb_bairros order by nome_bairro");
        
        ResultSet rs=null;//representação na memoria de um tabela
       
        
        try{
            conexao.rs.first();
           
            do{
                cb_bairros.addItem(conexao.rs.getString("nome_bairro"));
            }
            while (conexao.rs.next());{
              conexao.Desconecta();
            }
      
        }catch(Exception e){
            System.out.println(e.getMessage());
            conexao.Desconecta();
                
        }
        return rs;
    }
      public void ativarComponentes(){
        //Ativar as caixas
        txt_nome.setEnabled(true);
        txt_telefone.setEnabled(true);
        txt_endereco.setEnabled(true);
        txt_numero.setEnabled(true);
        txt_complemento.setEnabled(true);
        cb_bairros.setEnabled(true);
        txt_cep.setEnabled(true);
        bt_buscarCep.setEnabled(true);
    }
    public void desativarComponentes(){
        //Desativar as caixas
        txt_nome.setEnabled(false);
        txt_telefone.setEnabled(false);
        txt_endereco.setEnabled(false);
        txt_numero.setEnabled(false);
        txt_complemento.setEnabled(false);
        cb_bairros.setEnabled(false);
        bt_editar.setEnabled(false);
        bt_salvar.setEnabled(false);
        bt_excluir.setEnabled(false);
        txt_cep.setEnabled(false);
        bt_buscarCep.setEnabled(false);
    }
    public void limparComponentes(){
        //limpar as caixas
        txt_nome.setText("");
        txt_telefone.setText("");
        txt_endereco.setText("");
        txt_numero.setText("");
        txt_complemento.setText("");
        txt_cep.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscarCep;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JComboBox<String> cb_bairros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbSair;
    private javax.swing.JLabel lbl_icone;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_complemento;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

}
