/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.ConexaoBanco;

/**
 *
 * @author Escritorio
 */
public class RelatorioVenda extends javax.swing.JFrame {
    private ConexaoBanco conexao = new ConexaoBanco();
    private String dataPesquisar;
    private double totalvenda;
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private final DateFormat DATA = new SimpleDateFormat("yyyy-MM-dd");
    private Date data;
    /**
     * Creates new form RelatorioVenda
     */
    public RelatorioVenda() {
        initComponents();
      
    }
    public void buscarPorData(){
        
         String dia, mes, ano, res;
            res = txt_data.getText();
            dia = res.substring(0, res.indexOf('/'));
            mes = res.substring(res.indexOf('/')+1, res.lastIndexOf('/'));
            ano = res.substring(res.lastIndexOf('/')+1, res.length());
        
            res = ano+'-'+mes+'-'+dia;
            dataPesquisar = res;
            
        conexao.conecta();
        conexao.executaSQL("SELECT SUM(total) AS total_soma FROM tb_delivery WHERE data = '"+dataPesquisar+"'");
        
        try {
            conexao.rs.first();
            lbl_totalVenda.setText(decimal.format(conexao.rs.getDouble("total_soma")));
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.Desconecta();
    }
    public void buscarAberto(){
       conexao.conecta();
       conexao.executaSQL("SELECT SUM(total) AS total_concluida FROM tb_delivery WHERE data = '"+dataPesquisar+"'AND status = 'FECHADO'");
        
        try {
            conexao.rs.first();
            totalvenda = Double.parseDouble(conexao.rs.getString("total_concluida"));
            lbl_concuida.setText(decimal.format(totalvenda));
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.Desconecta();
    }
     public void buscarCancelado(){
       conexao.conecta();
       conexao.executaSQL("SELECT SUM(total) AS total_cancelado FROM tb_delivery WHERE data = '"+dataPesquisar+"'AND status = 'CANCELADO'");
        
        try {
            conexao.rs.first();
            lbl_concuida1.setText(decimal.format(conexao.rs.getDouble("total_cancelado")));
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.Desconecta();
    }
      public void buscarCartao(){
       double vendaCartao;
       conexao.conecta();
       conexao.executaSQL("SELECT SUM(total) AS total_cartao FROM tb_delivery WHERE data = '"+dataPesquisar+"'AND status = 'FECHADO' AND cartao = 'S'");
        
        try {
            conexao.rs.first();
            vendaCartao = Double.parseDouble(conexao.rs.getString("total_cartao"));
            lbl_vendaCartao.setText(decimal.format(vendaCartao));
            lbl_vendaDinheiro.setText(decimal.format(totalvenda - vendaCartao).replace(".", ","));
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.Desconecta();
    }
       public void buscarEntrega(){
      
       conexao.conecta();
       conexao.executaSQL("SELECT SUM(entrega) AS total_entrega FROM tb_delivery WHERE data = '"+dataPesquisar+"'AND status = 'FECHADO'");
        
        try {
            conexao.rs.first();
            lbl_entrega.setText(decimal.format(conexao.rs.getDouble("total_entrega")));
            
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.Desconecta();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_concuida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_concuida1 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        lbl_totalVenda = new javax.swing.JLabel();
        lbl_vendaCartao = new javax.swing.JLabel();
        lbl_vendaDinheiro = new javax.swing.JLabel();
        lbl_entrega = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_pesquisar = new javax.swing.JButton();
        bt_sair1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(170, 169, 149));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel2.setText("Total de Venda:");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setText("Vendas concluidas:");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("Total de Venda Cartão:");

        lbl_concuida.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_concuida.setForeground(new java.awt.Color(0, 102, 204));
        lbl_concuida.setText("0,00");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel4.setText("Total de Venda Dinheiro");

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel10.setText("Vendas Canceladas:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setText("Total de Entrega");

        lbl_concuida1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_concuida1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_concuida1.setText("0,00");

        txt_data.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N

        lbl_totalVenda.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_totalVenda.setForeground(new java.awt.Color(0, 153, 153));
        lbl_totalVenda.setText("0,00");

        lbl_vendaCartao.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_vendaCartao.setForeground(new java.awt.Color(153, 0, 153));
        lbl_vendaCartao.setText("0,00");

        lbl_vendaDinheiro.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_vendaDinheiro.setForeground(new java.awt.Color(0, 204, 51));
        lbl_vendaDinheiro.setText("0,00");

        lbl_entrega.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbl_entrega.setForeground(new java.awt.Color(255, 102, 0));
        lbl_entrega.setText("0,00");

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setText("Digite a Data:");

        bt_pesquisar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        bt_pesquisar.setText("Pequisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_sair1.setBackground(new java.awt.Color(170, 169, 149));
        bt_sair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        bt_sair1.setText("SAIR");
        bt_sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sair1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldFood.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/analytics.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_data))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_vendaCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_vendaDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_totalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_concuida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_concuida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_sair1)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_totalVenda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_concuida))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_concuida1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_vendaCartao))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_vendaDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_entrega)
                    .addComponent(bt_sair1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        buscarPorData();
        buscarAberto();
        buscarCancelado();
        buscarCartao();
        buscarEntrega();
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sair1ActionPerformed
        //sair da tela
       lbl_concuida.setText("0,00");
       lbl_entrega.setText("0,00");
       lbl_totalVenda.setText("0,00");
       lbl_vendaCartao.setText("0,00");
       lbl_vendaDinheiro.setText("0,00");
       txt_data.setText("");
       this.dispose();
    }//GEN-LAST:event_bt_sair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton bt_sair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_concuida;
    private javax.swing.JLabel lbl_concuida1;
    private javax.swing.JLabel lbl_entrega;
    private javax.swing.JLabel lbl_totalVenda;
    private javax.swing.JLabel lbl_vendaCartao;
    private javax.swing.JLabel lbl_vendaDinheiro;
    private javax.swing.JTextField txt_data;
    // End of variables declaration//GEN-END:variables
}
